jobs:
- template: build.yml  
  parameters:
    name: macOS
    pool:
      vmImage: 'macOS-10.13'

- template: build.yml  
  parameters:
    name: Linux
    pool:
      vmImage: 'Ubuntu-16.04'

# - template: build.yml  
  # parameters:
    # name: Windows
    # pool:
      # vmImage: 'vs2017-win2016'
