# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/d/Projects/Nitin/Java2CSharp/Java2CSharp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/d/Projects/Nitin/Java2CSharp/Java2CSharp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/Projects/Nitin/Java2CSharp/Java2CSharp/CMakeFiles /mnt/d/Projects/Nitin/Java2CSharp/Java2CSharp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/Projects/Nitin/Java2CSharp/Java2CSharp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sample1

# Build rule for target.
sample1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sample1
.PHONY : sample1

# fast build rule for target.
sample1/fast:
	$(MAKE) -f CMakeFiles/sample1.dir/build.make CMakeFiles/sample1.dir/build
.PHONY : sample1/fast

#=============================================================================
# Target rules for targets named tar

# Build rule for target.
tar: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tar
.PHONY : tar

# fast build rule for target.
tar/fast:
	$(MAKE) -f CMakeFiles/tar.dir/build.make CMakeFiles/tar.dir/build
.PHONY : tar/fast

CoreCLRHost.o: CoreCLRHost.cpp.o

.PHONY : CoreCLRHost.o

# target to build an object file
CoreCLRHost.cpp.o:
	$(MAKE) -f CMakeFiles/tar.dir/build.make CMakeFiles/tar.dir/CoreCLRHost.cpp.o
.PHONY : CoreCLRHost.cpp.o

CoreCLRHost.i: CoreCLRHost.cpp.i

.PHONY : CoreCLRHost.i

# target to preprocess a source file
CoreCLRHost.cpp.i:
	$(MAKE) -f CMakeFiles/tar.dir/build.make CMakeFiles/tar.dir/CoreCLRHost.cpp.i
.PHONY : CoreCLRHost.cpp.i

CoreCLRHost.s: CoreCLRHost.cpp.s

.PHONY : CoreCLRHost.s

# target to generate assembly for a file
CoreCLRHost.cpp.s:
	$(MAKE) -f CMakeFiles/tar.dir/build.make CMakeFiles/tar.dir/CoreCLRHost.cpp.s
.PHONY : CoreCLRHost.cpp.s

dynamicLinker/dynamicLinker.o: dynamicLinker/dynamicLinker.cpp.o

.PHONY : dynamicLinker/dynamicLinker.o

# target to build an object file
dynamicLinker/dynamicLinker.cpp.o:
	$(MAKE) -f CMakeFiles/tar.dir/build.make CMakeFiles/tar.dir/dynamicLinker/dynamicLinker.cpp.o
.PHONY : dynamicLinker/dynamicLinker.cpp.o

dynamicLinker/dynamicLinker.i: dynamicLinker/dynamicLinker.cpp.i

.PHONY : dynamicLinker/dynamicLinker.i

# target to preprocess a source file
dynamicLinker/dynamicLinker.cpp.i:
	$(MAKE) -f CMakeFiles/tar.dir/build.make CMakeFiles/tar.dir/dynamicLinker/dynamicLinker.cpp.i
.PHONY : dynamicLinker/dynamicLinker.cpp.i

dynamicLinker/dynamicLinker.s: dynamicLinker/dynamicLinker.cpp.s

.PHONY : dynamicLinker/dynamicLinker.s

# target to generate assembly for a file
dynamicLinker/dynamicLinker.cpp.s:
	$(MAKE) -f CMakeFiles/tar.dir/build.make CMakeFiles/tar.dir/dynamicLinker/dynamicLinker.cpp.s
.PHONY : dynamicLinker/dynamicLinker.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... sample1"
	@echo "... tar"
	@echo "... CoreCLRHost.o"
	@echo "... CoreCLRHost.i"
	@echo "... CoreCLRHost.s"
	@echo "... dynamicLinker/dynamicLinker.o"
	@echo "... dynamicLinker/dynamicLinker.i"
	@echo "... dynamicLinker/dynamicLinker.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

